### PR TITLE
Update creating-subset-of-an-alist

### PR DESCRIPTION
**Pull request by lassik**
@jcubic OK?

### CODE REVIEW

**Comment by lassik** [comment]
An operation that removes some items is usually called filtering (e.g. `filter` procedure in SRFI 1).

**Comment by lassik** [comment]
^ rebase to latest master, and tweak the code in Usage for consistent style with other pages

**Comment by jcubic** [comment]
looks good. We will need to link the recipes when they will be on the server the hash will no longer work.

**Comment by lassik** [comment]
> We will need to link the recipes when they will be on the server the hash will no longer work.

Link updated in https://github.com/schemedoc/cookbook/commit/b2a27efcff17080c2a5134c1a8c6f8cf86f2b5d3

Can be seen here: https://cookbook.scheme.org/filter-alist-keys/

**Pull request merged**
