### PR TITLE
N m holms

### PR DESCRIPTION
**Pull request by jcubic**
Collecting recipes by Nils M. Holm #34

### CODE REVIEW

**Comment by lassik** [comment]
Excellent work, thank you very much for taking on the task!

**Comment by lassik** [comment]
Can you add a `# Title` at the top of each `.md` file, and add the names of the new pages to [`www-index.scm`](https://github.com/schemedoc/cookbook/blob/cb7a7f12e5fdb9f60faa1a154f5afbaa128cc797/www-index.scm)?

**Comment by jcubic** [comment]
Yes, will add the title. I've forgotten about that. Also will update index file.

**Comment by lassik** [comment]
Thanks! Can we rename the pages a bit for consistency?

* Synchronize the title and filename for each page
* Use [imperative mood](https://www.grammar.com/imperative_mood)
* Use similar titles for similar pages

```
recipes/find-substring-in-string.md 
# Find substring in string

recipes/split-list-into-groups-by-comparator.md 
# Split list into groups by comparator

recipes/use-list-as-stack.md 
# Use list as stack

recipes/use-list-as-queue.md 
# Use list as queue
```

The `add-element-to-set` page could perhaps be turned into a general "Use list as set" page, to match the stack and queue pages?

```
recipes/use-list-as-set.md
# Use list as set
```

**Comment by jcubic** [comment]
Can you check those that are in the PR, for now, let's merge those. I will check and search for the new recipe later.

Will create new PR with next batch.

**Comment by lassik** [comment]
Very good!

Can you add `create-k-combinations-from-list` to the index and add a `# TItle` to the `.md` file? Otherwise, ready to merge.

**Comment by lassik** [comment]
Nevermind, I can make a commit to add those things. Looks good, all in all!

**Pull request merged**
